name: deta_data_source
description: DETA data source using deta provider
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  dio: ^4.0.6
  rest_data_source:
    path: ../rest_data_source
  dio_client_rest_api:
    path: ../dio_client_rest_api

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
