name: mini_campus
description: MiniCampus - A virtual campus app for students
publish_to: 'none' 
<<<<<<< HEAD
version: 1.0.3+3-pre
=======
version: 1.0.0+1
>>>>>>> dup-store

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase | google
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  firebase_messaging: ^11.2.8
  firebase_database: ^9.0.8

  # icons
  cupertino_icons: ^1.0.2
  flutter_vector_icons: ^1.0.0

  # components
  form_builder_validators: ^7.7.0

  # state management
  flutter_riverpod: ^2.0.0-dev.4

  # notification
  awesome_notifications: ^0.6.21

  # utilities
  shared_preferences: ^2.0.13
  google_fonts: ^2.3.1
  relative_scale: ^2.0.0
  intl:

  # custom libs
  mini_campus_core:
    git: https://github.com/DonnC-Lab/mini_campus_core.git

  mini_campus_core_libs:
    git: https://github.com/DonnC-Lab/mini_campus_core_libs.git

  mc_core_constants:
    git: https://github.com/DonnC-Lab/mc_core_constants.git

  mini_campus_core_components:
    git: https://github.com/DonnC-Lab/mini_campus_core_components.git

  # mini campus modules
  mc_campus_market:
    git: https://github.com/DonnC-Lab/mc_campus_market.git

  mc_feedback:
    git: https://github.com/DonnC-Lab/mc_feedback.git

  mc_learning:
    git: https://github.com/DonnC-Lab/mc_learning.git

  mc_lost_found:
    git: https://github.com/DonnC-Lab/mc_lost_found.git

  mc_survey:
    git: https://github.com/DonnC-Lab/mc_survey.git
  
dev_dependencies:
  build_runner: null
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable: ^6.1.4
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.6
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  fullscreen: true
  android_12:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/onboarding/