name: mini_campus
description: MiniCampus - A virtual campus app for students
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase | google
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  firebase_messaging: ^11.2.8
  firebase_database: ^9.0.8
  flutterfire_ui: ^0.3.6

  # icons
  cupertino_icons: ^1.0.2
  flutter_vector_icons: ^1.0.0
  flutter_svg: ^1.0.3

  # components
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^7.7.0
  styled_widget: ^0.4.0+3
  keyboard_actions: ^3.4.7
  animate_do: ^2.1.0
  circular_clip_route: ^0.2.0+2
  modal_bottom_sheet: ^2.0.1
  page_transition: ^2.0.5
  phone_number: ^0.12.0+1
  persistent_bottom_nav_bar_v2: ^4.1.3
  photo_view: ^0.13.0
  flutter_staggered_grid_view: ^0.6.1
  toggle_switch: ^1.4.0
  

  # file IO
  image_picker: ^0.8.4+11
  file_picker: ^4.5.1
  flutter_cached_pdfview: ^0.4.1

  # state management
  flutter_riverpod: ^2.0.0-dev.4

  # notification
  fluttertoast: ^8.0.9
  flash: ^2.0.3+2

  # deta
  deta: ^0.0.3+1
  dio_client_deta_api: ^0.0.1

  # utilities
  dio: ^4.0.4
  freezed_annotation: ^1.1.0
  timeago: ^3.2.2
  url_launcher: ^6.0.20
  shared_preferences: ^2.0.13
  lottie: ^1.2.2
  linkable: ^3.0.1
  material_floating_search_bar: ^0.3.7
  google_fonts: ^2.3.1
  pin_code_fields: ^7.3.0
  relative_scale: ^2.0.0
  localregex: ^3.0.3
  timer_button:
  intl:

  # misc
  faker: ^2.0.0
  

dev_dependencies:
  build_runner: null
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/