name: mini_campus
description: MiniCampus - A virtual campus app for students
publish_to: 'none' 
version: 1.0.2+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase | google
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  firebase_messaging: ^11.2.8
  firebase_database: ^9.0.8

  # icons
  cupertino_icons: ^1.0.2
  flutter_vector_icons: ^1.0.0

  # components
  form_builder_validators: ^7.7.0

  # state management
  flutter_riverpod: ^2.0.0-dev.4

  # notification
  awesome_notifications: ^0.6.21

  # utilities
  shared_preferences: ^2.0.13
  google_fonts: ^2.3.1
  relative_scale: ^2.0.0
  intl:

  flutter_flavor: ^3.0.3

  # custom mc libs
  mini_campus_core:
    git: 
      url: https://github.com/DonnC-Lab/mini_campus_core.git
      ref: main

  mini_campus_core_libs:
    git: 
      url: https://github.com/DonnC-Lab/mini_campus_core_libs.git 
      ref: main

  mc_core_constants:
    git: 
      url: https://github.com/DonnC-Lab/mc_core_constants.git
      ref: main # branch name

  mini_campus_core_components:
    git:
      url: https://github.com/DonnC-Lab/mini_campus_core_components.git
      ref: main

  # mini campus modules
  mc_campus_market:
    git: 
      url: https://github.com/DonnC-Lab/mc_campus_market.git
      ref: main

  mc_feedback:
    git: 
      url: https://github.com/DonnC-Lab/mc_feedback.git 
      ref: main

  mc_learning:
    git: 
      url: https://github.com/DonnC-Lab/mc_learning.git
      ref: main

  mc_lost_found:
    git: 
      url: https://github.com/DonnC-Lab/mc_lost_found.git
      ref: main

  mc_survey:
    git: 
      url: https://github.com/DonnC-Lab/mc_survey.git
      ref: main
       
dev_dependencies:
  build_runner: null
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable: ^6.1.4
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.6
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  fullscreen: true
  android_12:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/onboarding/

flutter_flavor:
  dimensions:
    android: "flutter-flavor"

  flavors:
    dev:
      android:
        name: "MiniCampus Dev"
        #applicationId: "com.donnclab.mini_campus.dev"
        applicationId: "com.donnclab.ris.mini_campus"
        versionNameSuffix: "-dev"

    # SHOULD NOT BE CHANGED
    prod:
      app:
        name: "MiniCampus"
        id: "com.donnclab.mini_campus"

      android:
        name: "MiniCampus"
        applicationId: "com.donnclab.mini_campus"