name: mini_campus
description: MiniCampus - A virtual campus app for students
publish_to: "none"
version: 1.0.3+3

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  # notification
  awesome_notifications: ^0.6.21

  # firebase | google
  cloud_firestore: ^3.1.10

  # icons
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  firebase_database: ^9.0.8
  firebase_messaging: ^11.2.8
  firebase_storage: ^10.2.9
  flutter:
    sdk: flutter

  flutter_flavor: ^3.0.3

  # state management
  flutter_riverpod: ^2.0.0-dev.9
  flutter_vector_icons: ^1.0.0

  # components
  form_builder_validators: ^7.7.0

  # utilities
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/onboarding/

flutter_flavor:
  dimensions:
    android: "flutter-flavor"

  flavors:
    dev:
      android:
        name: "[Dev] MiniCampus"
        # can be changed if setting up firebase emulator, should be same as app_id in setting up
        # firebase emulator in `melos.yaml`
        applicationId: "com.dcl.mc.dev"
        versionNameSuffix: "-dev"

    # SHOULD NOT BE CHANGED
    prod:
      app:
        name: "MiniCampus"
        id: "com.donnclab.mini_campus"

      android:
        name: "MiniCampus"
        applicationId: "com.donnclab.mini_campus"
