name: client_rest_api
description: a generic client rest api interface, copied from https://github.com/yeikel16/deta-dart
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
