name: mini_campus_services
description: Mini Campus library helper services
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_riverpod: ^2.0.0-dev.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
