// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdTO1Iio_5R54esvUV0nKTJE03nyZZTmU',
    appId: '1:458171839784:android:1d26ac61f0fbbb2105cc1d',
    messagingSenderId: '458171839784',
    projectId: 'mini-campus-ris',
    storageBucket: 'mini-campus-ris.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOtYPNxmseuh5K7-3gmVmBkeAZrZXs0lc',
    appId: '1:458171839784:ios:370695f018f6556505cc1d',
    messagingSenderId: '458171839784',
    projectId: 'mini-campus-ris',
    storageBucket: 'mini-campus-ris.appspot.com',
    iosClientId:
        '458171839784-4b6he7t1p0ajek77c9vtqtdp8bt17blm.apps.googleusercontent.com',
    iosBundleId: 'com.donnclab.ris',
  );
}
