name: learning
description: Learning module via peer 2 peer experience
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
