name: mini_campus_core
description: A Mini Campus package with core project features
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  awesome_notifications: ^0.6.21
  circular_clip_route: ^0.2.0+3
  cloud_firestore: ^3.4.9
  deta_data_source:
    path: ../deta_data_source
  flutter:
    sdk: flutter
  flutter_advanced_avatar: ^1.1.0
  flutter_riverpod: ^2.0.2
  flutter_svg: ^1.1.5
  flutter_vector_icons: ^2.0.0
  flutter_web_browser: ^0.17.1
  form_builder_validators: ^8.3.0
  freezed_annotation: ^2.1.0
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  intro_slider: ^4.2.0
  json_annotation: ^4.7.0
  keyboard_actions: ^4.1.0
  localregex: ^4.0.0
  mini_campus_components:
    path: ../mini_campus_components
  mini_campus_constants:
    path: ../mini_campus_constants
  mini_campus_services:
    path: ../mini_campus_services
  modal_bottom_sheet: ^2.1.2
  page_transition: ^2.0.9
  phone_number: ^1.0.0
  relative_scale: ^2.0.0
  shared_preferences: ^2.0.15
  timeago: ^3.3.0
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable: ^6.4.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
