name: campus_market
description: Campus Market, an e-commerce like experience for students
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  fancy_shimmer_image: ^2.0.2
  flutter:
    sdk: flutter
  flutterfire_ui: ^0.4.3+12
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  linkable: ^3.0.1
  material_floating_search_bar: ^0.3.7
  mini_campus_components:
    path: ../mini_campus_components
  mini_campus_constants:
    path: ../mini_campus_constants
  mini_campus_core:
    path: ../mini_campus_core
  mini_campus_services:
    path: ../mini_campus_services
  persistent_bottom_nav_bar_v2: ^4.2.5
  staggered_grid_view_flutter: ^0.0.4

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
