// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSvwkP7C5SYxUWqzfADngJJht2fY1B6ro',
    appId: '1:17596106485:web:fec7e18ecbfe5f1355a7bc',
    messagingSenderId: '17596106485',
    projectId: 'mini-campus-app',
    authDomain: 'mini-campus-app.firebaseapp.com',
    databaseURL: 'https://mini-campus-app-default-rtdb.firebaseio.com',
    storageBucket: 'mini-campus-app.appspot.com',
    measurementId: 'G-7G9X7THZYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQlWPrGj3Gag182x3YG9fTGdhcyML3On0',
    appId: '1:17596106485:android:564c3739e3d8ceb255a7bc',
    messagingSenderId: '17596106485',
    projectId: 'mini-campus-app',
    databaseURL: 'https://mini-campus-app-default-rtdb.firebaseio.com',
    storageBucket: 'mini-campus-app.appspot.com',
  );
}
